language: node_js # 指定语言环境
node_js:
  - 10 # use nodejs v10 LTS
dist: trusty # 指定系统版本。trusty 是指 Ubuntu 14.04 发行版的名称
sudo: false # 是否需要 sudo 权限
cache: npm

branches:
  only:
  - hexo

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_success:
#   - git clone https://${GIT_REPO} .deploy_git
#   - cd .deploy_git
#   - git checkout master
#   - cd ../
#   - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git init
  - git config user.name "${GIT_NAME}"
  - git config user.email "${GIT_EMAIL}"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y%m%d %H:%M"`"
  - git push --force --quiet "https://${GIT_REPO_TOKEN}@${GIT_REPO}" master:master

# deploy:
#   provider: master
#   skip-cleanup: true
#   github-token: $GIT_REPO_TOKEN
#   keep-history: true
#   on:
#     branch: hexo
#   local-dir: public

notifications:
  email: true